
stages:
  - deploy

# ===
# Settings
variables:
  #Docker
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://localhost:2375

  #Rancher
  RANCHER_URL_PRODUCTION: https://rancher2.vorwaerts.com
  RANCHER_ACCESS_KEY: token-dq9lz
  RANCHER_SECRET_KEY: nxvfjxdv5ds2jb6v76pxns7kzbhkx9r9b9882ffd6gpm5pdk6xsbxv

#alpine/helm:latest
deploy:yamls:
  stage: deploy
  #image: thorstenhans/helm3
  image: linkyard/docker-helm
  variables:
    NAMESPACE: 'custom-metrics'
  before_script:
    - mkdir $HOME/prometheus-adapter-charts
    - cd $HOME/prometheus-adapter-charts
    - cat $KUBECONFIG_CONTENT > $HOME/.kube/config
    - export KUBECONFIG="$HOME/.kube/config"
    - apk update  && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl 
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
    - helm init
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo update 

  script:
    #- helm repo add stable https://kubernetes-charts.storage.googleapis.com
    #- helm repo update
    - helm install adapter stable/prometheus-adapter --values $CI_PROJECT_DIR/values.yaml --namespace "$NAMESPACE"